from __future__ import annotations

import logging
from importlib import import_module

from core.email.types import MountedTemplate

# Generated by `fasterapi email mount`. Each template is imported on its own, so one broken template
# is logged and skipped instead of disabling every email.
_MODULES = [
    "email_templates.starter_template",
]


def get_mounted_templates() -> list[MountedTemplate]:
    templates: list[MountedTemplate] = []
    for name in _MODULES:
        try:
            module = import_module(name)
        except Exception:
            logging.getLogger(__name__).exception("Email template module %s failed to import", name)
            continue
        templates.append(
            MountedTemplate(
                key=module.TEMPLATE_KEY,
                subject=module.SUBJECT,
                render_html=module.render_html,
                render_text=module.render_text,
            )
        )
    return templates
